### ISSUE TITLE
Moment missing from the frontend

### ISSUE THREAD

**Issue by therobear** [strapi/strapi-starter-react-blog#1]
Hello,

When trying to run the front end, an error occurs regarding react-moment. The error it reports is:
`Can't resolve 'moment' in ..\strapi-react-blog\frontend\node_modules\react-moment\dist`

To resolve the issue, moment has to be installed. Moment is missing from the package.json file.

**Comment by pierreburgy** [comment]
Good catch! @Mcastres I created a PR for this.
