### ISSUE TITLE
yarn setup:yarn command doesn't exist

### ISSUE THREAD

**Issue by NikhilVerma** [strapi/strapi-starter-react-blog#14]
According to the page : https://strapi.io/blog/strapi-starter-react-blog

```
git clone https://github.com/strapi/strapi-starter-react-blog.git
cd strapi-starter-react-blog

# Using yarn
yarn setup:yarn
```

But there is no `package.json` in the root folder of the repo. So this instruction doesn't work.

**Comment by Mcastres** [comment]
Sorry @NikhilVerma I changed the way you start your servers :)
Please check the new documentation
