### ISSUE TITLE
Using parseInt() on id in Query causes GraphQL error

### ISSUE THREAD

**Issue by robinleboe** [strapi/strapi-starter-react-blog#3]
The issue manifests as a GraphQL error: "graphQLErrors:[{message:Cast to ObjectId failed for value...}]" thrown by the conditional in src/components/Query/index.js

The parseInt() function in src/components/Query/index.js causes the error:
```
const { data, loading, error } = useQuery(query, {
    variables: { id: parseInt(id) }
  });
```
Once parseInt() is removed the application works correctly.

I am using MongoDB version v4.2.3 and have not tested with sqlite3, which is used in the quickstart.

**Comment by Mcastres** [comment]
Thanks, I removed it in this commit: https://github.com/strapi/strapi-starter-react-blog/commit/90edbad5d7239ec148c99b4cb7ebc97a48912425 :)
