### ISSUE TITLE
The "path" argument must be of type string. 

### ISSUE THREAD

**Issue by litehacker** [strapi/strapi-starter-react-blog#7]
**Node Version**
v13.8.0
npm Version
**6.14.0**
I have followed you tutorial for starting the project. Have no problems on Backend, but the frontend server gives the error here:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:118:11)
    at Object.join (path.js:1039:7)
```

--------------------------------------------------------------
Solution for me:

1. Delete node_modules\ folder
2. Delete package-lock.json file
3. Rewrite the package.json file from "react-scripts": "3.x.x" to "react-scripts": "^3.4.0"
4. npm run build:npm
5. npm run develop:npm
(followed the [tutorial](https://strapi.io/blog/strapi-starter-react-blog#comment-4775297893))

[SOURCE](https://stackoverflow.com/a/60251427/4307534) of the solution.

**Comment by OnlineDanceEvents** [comment]
Experiencing the same 👍

**Comment by OnlineDanceEvents** [comment]
Oh found it (resolved by this below). Basically downgrade to version 10.0.0
![image](https://user-images.githubusercontent.com/64803049/81016981-60790980-8e59-11ea-8e39-6aef2660ce8a.png)

https://github.com/facebook/create-react-app/issues/8499

**Comment by litehacker** [comment]
> facebook/create-react-app#8499

Haven't check `react-dev-utils` , but updated the package version of    ` "react-scripts": "^3.4.1"` it worked. [Source](https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re/60242323#60242323) <-
