### ISSUE TITLE
heap limit allocation failed

### ISSUE THREAD

**Issue by TanawutWatthana** [strapi/strapi-starter-react-blog#9]
{
  "header": {
    "reportVersion": 2,
    "event": "Allocation failed - JavaScript heap out of memory",
    "trigger": "FatalError",
    "filename": "report.20200424.201719.6293.0.001.json",
    "dumpEventTime": "2020-04-24T20:17:19Z",
    "dumpEventTimeStamp": "1587759439737",
    "processId": 6293,
    "threadId": null,
    "cwd": "/home/inmad/NJS_StrapiReact/backend",
    "commandLine": [
      "node",
      "/home/inmad/NJS_StrapiReact/backend/node_modules/.bin/strapi",
      "build"
    ],
    "nodejsVersion": "v12.16.2",
    "glibcVersionRuntime": "2.27",
    "glibcVersionCompiler": "2.17",
    "wordSize": 64,
    "arch": "x64",
    "platform": "linux",
    "componentVersions": {
      "node": "12.16.2",
      "v8": "7.8.279.23-node.34",
      "uv": "1.34.2",
      "zlib": "1.2.11",
      "brotli": "1.0.7",
      "ares": "1.15.0",
      "modules": "72",
      "nghttp2": "1.40.0",
      "napi": "5",
      "llhttp": "2.0.4",
      "http_parser": "2.9.3",
      "openssl": "1.1.1e",
      "cldr": "36.0",
      "icu": "65.1",
      "tz": "2019c",
      "unicode": "12.1"
    },
    "release": {
      "name": "node",
      "lts": "Erbium",
      "headersUrl": "https://nodejs.org/download/release/v12.16.2/node-v12.16.2-headers.tar.gz",
      "sourceUrl": "https://nodejs.org/download/release/v12.16.2/node-v12.16.2.tar.gz"
    },
    "osName": "Linux",
    "osRelease": "4.15.0-96-generic",
    "osVersion": "#97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020",
    "osMachine": "x86_64",
    "cpus": [
      {
        "model": "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz",
        "speed": 2304,
        "user": 3512300,
        "nice": 0,
        "sys": 2503600,
        "idle": 37510400,
        "irq": 0
      }
    ],
    "networkInterfaces": [
      {
        "name": "lo",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "127.0.0.1",
        "netmask": "255.0.0.0",
        "family": "IPv4"
      },
      {
        "name": "enp0s3",
        "internal": false,
        "mac": "08:00:27:0b:c6:76",
        "address": "192.168.1.99",
        "netmask": "255.255.255.0",
        "family": "IPv4"
      },
      {
        "name": "flannel.1",
        "internal": false,
        "mac": "66:93:5a:d6:c6:21",
        "address": "10.1.15.0",
        "netmask": "255.255.255.255",
        "family": "IPv4"
      },
      {
        "name": "lo",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "::1",
        "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
        "family": "IPv6",
        "scopeid": 0
      },
      {
        "name": "enp0s3",
        "internal": false,
        "mac": "08:00:27:0b:c6:76",
        "address": "fe80::a00:27ff:fe0b:c676",
        "netmask": "ffff:ffff:ffff:ffff::",
        "family": "IPv6",
        "scopeid": 2
      },
      {
        "name": "flannel.1",
        "internal": false,
        "mac": "66:93:5a:d6:c6:21",
        "address": "fe80::6493:5aff:fed6:c621",
        "netmask": "ffff:ffff:ffff:ffff::",
        "family": "IPv6",
        "scopeid": 6
      }
    ],
    "host": "se-vb"
  },
  "javascriptStack": {
    "message": "No stack.",
    "stack": [
      "Unavailable."
    ]
  },
  "nativeStack": [
    {
      "pc": "0x0000000000b40285",
      "symbol": "report::TriggerNodeReport(v8::Isolate*, node::Environment*, char const*, char const*, std::string const&, v8::Local<v8::String>) [node]"
    },
    {
      "pc": "0x0000000000a033ef",
      "symbol": "node::OnFatalError(char const*, char const*) [node]"
    },
    {
      "pc": "0x0000000000b76ffe",
      "symbol": "v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]"
    },
    {
      "pc": "0x0000000000b77379",
      "symbol": "v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]"
    },
    {
      "pc": "0x0000000000d23ad5",
      "symbol": " [node]"
    },
    {
      "pc": "0x0000000000d24166",
      "symbol": "v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]"
    },
    {
      "pc": "0x0000000000d309e5",
      "symbol": "v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]"
    },
    {
      "pc": "0x0000000000d31895",
      "symbol": "v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]"
    },
    {
      "pc": "0x0000000000d3434c",
      "symbol": "v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]"
    },
    {
      "pc": "0x0000000000cfaf1b",
      "symbol": "v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]"
    },
    {
      "pc": "0x000000000103d85e",
      "symbol": "v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]"
    },
    {
      "pc": "0x00000000013c03d9",
      "symbol": " [node]"
    }
  ],
  "javascriptHeap": {
    "totalMemory": 518189056,
    "totalCommittedMemory": 516693560,
    "usedMemory": 510616736,
    "availableMemory": 12304144,
    "memoryLimit": 528482304,
    "heapSpaces": {
      "read_only_space": {
        "memorySize": 262144,
        "committedMemory": 33088,
        "capacity": 32808,
        "used": 32808,
        "available": 0
      },
      "new_space": {
        "memorySize": 2097152,
        "committedMemory": 1172600,
        "capacity": 1047456,
        "used": 122960,
        "available": 924496
      },
      "old_space": {
        "memorySize": 472522752,
        "committedMemory": 472368416,
        "capacity": 470155992,
        "used": 470117048,
        "available": 38944
      },
      "code_space": {
        "memorySize": 1478656,
        "committedMemory": 1291616,
        "capacity": 1215936,
        "used": 1215936,
        "available": 0
      },
      "map_space": {
        "memorySize": 4984832,
        "committedMemory": 4984320,
        "capacity": 2466400,
        "used": 2466400,
        "available": 0
      },
      "large_object_space": {
        "memorySize": 36220928,
        "committedMemory": 36220928,
        "capacity": 36117040,
        "used": 36117040,
        "available": 0
      },
      "code_large_object_space": {
        "memorySize": 622592,
        "committedMemory": 622592,
        "capacity": 544544,
        "used": 544544,
        "available": 0
      },
      "new_large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 1047456,
        "used": 0,
        "available": 1047456
      }
    }
  },
  "resourceUsage": {
    "userCpuSeconds": 55.4668,
    "kernelCpuSeconds": 1.55511,
    "cpuConsumptionPercent": 57.0219,
    "maxRss": 507637760,
    "pageFaults": {
      "IORequired": 1257,
      "IONotRequired": 199407
    },
    "fsActivity": {
      "reads": 232792,
      "writes": 12848
    }
  },
  "uvthreadResourceUsage": {
    "userCpuSeconds": 27.6394,
    "kernelCpuSeconds": 0.6959,
    "cpuConsumptionPercent": 28.3353,
    "fsActivity": {
      "reads": 118584,
      "writes": 0
    }
  },
  "libuv": [
  ],
  "workers": [
  ],
  "environmentVariables": {
    "LESSOPEN": "| /usr/bin/lesspipe %s",
    "npm_config_cache_lock_stale": "60000",
    "npm_config_ham_it_up": "",
    "npm_config_legacy_bundling": "",
    "npm_config_sign_git_tag": "",
    "MAIL": "/var/mail/inmad",
    "USER": "inmad",
    "SSH_CLIENT": "192.168.1.103 61168 22",
    "npm_package_dependencies_strapi_plugin_content_type_builder": "3.0.0-beta.20",
    "npm_config_user_agent": "yarn/1.22.4 npm/? node/v12.16.2 linux x64",
    "npm_config_version_commit_hooks": "true",
    "npm_config_always_auth": "",
    "npm_package_scripts_strapi": "strapi",
    "npm_config_bin_links": "true",
    "npm_config_key": "",
    "npm_config_init_version": "1.0.0",
    "npm_config_allow_same_version": "",
    "npm_config_description": "true",
    "npm_config_fetch_retries": "2",
    "npm_config_heading": "npm",
    "npm_config_if_present": "",
    "npm_config_user": "1000",
    "npm_node_execpath": "/home/inmad/.nvm/versions/node/v12.16.2/bin/node",
    "SHLVL": "1",
    "npm_config_prefer_online": "",
    "npm_config_noproxy": "",
    "HOME": "/home/inmad",
    "OLDPWD": "/home/inmad/NJS_StrapiReact",
    "npm_package_dependencies_strapi_admin": "3.0.0-beta.20",
    "npm_config_force": "",
    "SSH_TTY": "/dev/pts/0",
    "NVM_BIN": "/home/inmad/.nvm/versions/node/v12.16.2/bin",
    "npm_package_dependencies_strapi_utils": "3.0.0-beta.20",
    "npm_config_only": "",
    "npm_config_read_only": "",
    "npm_package_engines_node": ">=10.0.0",
    "npm_config_init_license": "MIT",
    "npm_config_cache_min": "10",
    "YARN_WRAP_OUTPUT": "false",
    "npm_config_version_tag_prefix": "v",
    "npm_config_editor": "vi",
    "npm_config_rollback": "true",
    "npm_config_tag_version_prefix": "v",
    "npm_config_cache_max": "Infinity",
    "npm_config_timing": "",
    "npm_config_userconfig": "/home/inmad/.npmrc",
    "npm_package_dependencies_strapi_plugin_graphql": "3.0.0-beta.20",
    "npm_config_engine_strict": "",
    "npm_config_init_author_name": "",
    "npm_config_init_author_url": "",
    "npm_config_preid": "",
    "npm_config_tmp": "/tmp",
    "npm_package_description": "A Strapi application",
    "npm_config_depth": "Infinity",
    "npm_config_package_lock_only": "",
    "npm_config_save_dev": "",
    "npm_config_usage": "",
    "NVM_DIR": "/home/inmad/.nvm",
    "npm_package_readmeFilename": "README.md",
    "npm_config_metrics_registry": "https://registry.yarnpkg.com/",
    "npm_config_cafile": "",
    "npm_config_otp": "",
    "npm_config_package_lock": "true",
    "npm_config_progress": "true",
    "npm_config_https_proxy": "",
    "npm_config_save_prod": "",
    "npm_package_dependencies_strapi": "3.0.0-beta.20",
    "npm_package_dependencies_strapi_plugin_email": "3.0.0-beta.20",
    "npm_config_audit": "true",
    "npm_config_cidr": "",
    "npm_config_onload_script": "",
    "npm_config_sso_type": "oauth",
    "LOGNAME": "inmad",
    "npm_config_rebuild_bundle": "true",
    "npm_config_save_bundle": "",
    "npm_config_shell": "/bin/bash",
    "_": "/home/inmad/.nvm/versions/node/v12.16.2/bin/yarn",
    "npm_package_private": "true",
    "npm_config_dry_run": "",
    "npm_config_format_package_lock": "true",
    "npm_config_prefix": "/home/inmad/.nvm/versions/node/v12.16.2",
    "npm_package_scripts_develop": "strapi develop",
    "npm_package_strapi_uuid": "e9cf5d8b-5389-4579-869f-bcd3a078c343",
    "npm_config_scope": "",
    "npm_config_registry": "https://registry.yarnpkg.com/",
    "npm_config_browser": "",
    "npm_config_cache_lock_wait": "10000",
    "npm_config_ignore_prepublish": "",
    "npm_config_save_optional": "",
    "npm_config_searchopts": "",
    "npm_config_versions": "",
    "XDG_SESSION_ID": "1",
    "TERM": "xterm",
    "npm_config_cache": "/home/inmad/.npm",
    "npm_config_proxy": "",
    "npm_config_send_metrics": "",
    "npm_package_scripts_start": "strapi start",
    "npm_config_global_style": "",
    "npm_config_ignore_scripts": "",
    "npm_config_version": "",
    "npm_config_local_address": "",
    "npm_config_viewer": "man",
    "npm_config_node_gyp": "/home/inmad/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
    "PATH": "/home/inmad/.nvm/versions/node/v12.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/inmad/NJS_StrapiReact/backend/node_modules/.bin:/home/inmad/NJS_StrapiReact/backend/node_modules/.bin:/home/inmad/NJS_StrapiReact/node_modules/.bin:/home/inmad/node_modules/.bin:/home/node_modules/.bin:/node_modules/.bin:/home/inmad/.nvm/versions/node/v12.16.2/bin:/tmp/yarn--1587759322375-0.06179811170280369:/home/inmad/NJS_StrapiReact/backend/node_modules/.bin:/home/inmad/.config/yarn/link/node_modules/.bin:/home/inmad/.yarn/bin:/home/inmad/.nvm/versions/node/v12.16.2/libexec/lib/node_modules/npm/bin/node-gyp-bin:/home/inmad/.nvm/versions/node/v12.16.2/lib/node_modules/npm/bin/node-gyp-bin:/home/inmad/.nvm/versions/node/v12.16.2/bin/node_modules/npm/bin/node-gyp-bin:/home/inmad/.nvm/versions/node/v12.16.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",
    "NODE": "/home/inmad/.nvm/versions/node/v12.16.2/bin/node",
    "npm_package_name": "backend",
    "npm_config_audit_level": "low",
    "npm_config_prefer_offline": "",
    "XDG_RUNTIME_DIR": "/run/user/1000",
    "npm_package_dependencies_strapi_plugin_upload": "3.0.0-beta.20",
    "npm_config_color": "true",
    "npm_config_sign_git_commit": "",
    "npm_config_fetch_retry_mintimeout": "10000",
    "npm_config_maxsockets": "50",
    "npm_config_offline": "",
    "npm_config_sso_poll_frequency": "500",
    "LANG": "en_US.UTF-8",
    "npm_config_umask": "0002",
    "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:",
    "npm_package_dependencies_sqlite3": "latest",
    "npm_config_fund": "true",
    "npm_config_fetch_retry_maxtimeout": "60000",
    "npm_config_loglevel": "notice",
    "npm_config_logs_max": "10",
    "npm_config_message": "%s",
    "npm_lifecycle_script": "strapi build",
    "npm_package_dependencies_strapi_connector_bookshelf": "3.0.0-beta.20",
    "npm_config_version_git_message": "v%s",
    "npm_config_ca": "",
    "npm_config_cert": "",
    "npm_config_global": "",
    "npm_config_link": "",
    "SHELL": "/bin/bash",
    "npm_package_version": "0.1.0",
    "npm_package_dependencies_knex": "<0.20.0",
    "npm_config_access": "",
    "npm_config_also": "",
    "npm_config_save": "true",
    "npm_config_unicode": "true",
    "npm_lifecycle_event": "build",
    "npm_package_scripts_build": "strapi build",
    "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"build\"],\"original\":[\"run\",\"build\"]}",
    "npm_config_before": "",
    "npm_config_long": "",
    "npm_config_production": "",
    "npm_config_searchlimit": "20",
    "npm_config_unsafe_perm": "true",
    "npm_config_update_notifier": "true",
    "LESSCLOSE": "/usr/bin/lesspipe %s %s",
    "npm_config_auth_type": "legacy",
    "npm_config_node_version": "12.16.2",
    "npm_config_tag": "latest",
    "npm_package_dependencies_strapi_plugin_content_manager": "3.0.0-beta.20",
    "npm_config_version_git_tag": "true",
    "npm_config_git_tag_version": "true",
    "npm_config_commit_hooks": "true",
    "npm_config_script_shell": "",
    "npm_config_shrinkwrap": "true",
    "npm_package_license": "MIT",
    "npm_config_strict_ssl": "true",
    "npm_config_fetch_retry_factor": "10",
    "npm_config_save_exact": "",
    "npm_config_dev": "",
    "npm_config_globalconfig": "/home/inmad/.nvm/versions/node/v12.16.2/etc/npmrc",
    "npm_config_init_module": "/home/inmad/.npm-init.js",
    "npm_config_parseable": "",
    "PWD": "/home/inmad/NJS_StrapiReact/backend",
    "npm_config_globalignorefile": "/home/inmad/.nvm/versions/node/v12.16.2/etc/npmignore",
    "npm_execpath": "/home/inmad/.nvm/versions/node/v12.16.2/lib/node_modules/npm/bin/npm-cli.js",
    "SSH_CONNECTION": "192.168.1.103 61168 192.168.1.99 22",
    "NVM_CD_FLAGS": "",
    "XDG_DATA_DIRS": "/usr/local/share:/usr/share:/var/lib/snapd/desktop",
    "npm_package_author_name": "A Strapi developer",
    "npm_package_engines_npm": ">=6.0.0",
    "npm_config_cache_lock_retries": "10",
    "npm_config_searchstaleness": "900",
    "npm_config_save_prefix": "^",
    "npm_config_node_options": "",
    "npm_config_scripts_prepend_node_path": "warn-only",
    "npm_config_group": "1000",
    "npm_config_init_author_email": "",
    "npm_config_searchexclude": "",
    "npm_package_dependencies_strapi_plugin_users_permissions": "3.0.0-beta.20",
    "npm_config_git": "git",
    "npm_config_optional": "true",
    "INIT_CWD": "/home/inmad/NJS_StrapiReact/backend",
    "npm_config_json": "",
    "WEBPACK_DEV_SERVER": "true"
  },
  "userLimits": {
    "core_file_size_blocks": {
      "soft": 0,
      "hard": "unlimited"
    },
    "data_seg_size_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "file_size_blocks": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "max_locked_memory_bytes": {
      "soft": 16777216,
      "hard": 16777216
    },
    "max_memory_size_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "open_files": {
      "soft": 1048576,
      "hard": 1048576
    },
    "stack_size_bytes": {
      "soft": 8388608,
      "hard": "unlimited"
    },
    "cpu_time_seconds": {
      "soft": "unlimited",
      "hard": "unlimited"
    },
    "max_user_processes": {
      "soft": 3695,
      "hard": 3695
    },
    "virtual_memory_kbytes": {
      "soft": "unlimited",
      "hard": "unlimited"
    }
  },
  "sharedObjects": [
    "linux-vdso.so.1",
    "/lib/x86_64-linux-gnu/libdl.so.2",
    "/usr/lib/x86_64-linux-gnu/libstdc++.so.6",
    "/lib/x86_64-linux-gnu/libm.so.6",
    "/lib/x86_64-linux-gnu/libgcc_s.so.1",
    "/lib/x86_64-linux-gnu/libpthread.so.0",
    "/lib/x86_64-linux-gnu/libc.so.6",
    "/lib64/ld-linux-x86-64.so.2"
  ]
}

**Comment by lauriejim** [comment]
Hello! I'm closing this issue.
There is no message.
